# Default config for the RL agent in the autonomous driving environment
training:
  total_timesteps: 1000000
  batch_size: 64
  n_steps: 2048
  gamma: 0.99
  learning_rate: 0.0003
  ent_coef: 0.01
  clip_range: 0.2
  n_epochs: 10
  gae_lambda: 0.95

environment:
  frame_skip: 1
  max_episode_steps: 1000
  obs_stack: 3
  reward_config:
    detection_reward: 0.1
    fps_reward: 0.05
    collision_penalty: -1.0
    success_reward: 1.0

detector:
  ssd:
    conf_thresh: 0.5
    model: "ssd300_vgg16"
    weights: "DEFAULT"
  yolo:
    conf_thresh: 0.5
    iou_thresh: 0.45
    weights: "yolov9-c.pt"  
    img_size: 640

roi:
  min_size: 0.2
  max_size: 0.8
  overlap_thresh: 0.5