# Highway driving scenario configuration
environment:
  scenario: "highway"
  town: "Town07"  
  weather:
    - "ClearNoon"
    - "ClearSunset"
    - "WetNoon"
    - "SoftRainNoon"
  
  # Traffic parameters
  num_vehicles: 80  
  num_pedestrians: 0  
  vehicle_types:
    - "vehicle.audi.a2"
    - "vehicle.audi.etron"
    - "vehicle.audi.tt"
    - "vehicle.bmw.grandtourer"
    - "vehicle.chevrolet.impala"
    - "vehicle.dodge.charger_police"
    - "vehicle.ford.mustang"
    - "vehicle.jeep.wrangler_rubicon"
    - "vehicle.lincoln.mkz2017"
    - "vehicle.mercedes.coupe"
    - "vehicle.mini.cooperst"
    - "vehicle.nissan.micra"
    - "vehicle.nissan.patrol"
    - "vehicle.seat.leon"
    - "vehicle.tesla.cybertruck"
    - "vehicle.tesla.model3"
    - "vehicle.toyota.prius"
    - "vehicle.volkswagen.t2"

  # Road characteristics
  junction_density: 0.1  
  lane_width: 3.5  
  speed_limit: 120  # km/h

  # Object detection challenges
  occlusion_probability: 0.1
  small_object_scale: 0.3  
  high_speed_objects: true

  # Reward configuration
  reward_config:
    detection_reward: 1.2  
    fps_reward: 0.7  
    collision_penalty: -20.0  
    pedestrian_detection_bonus: 0.0  
    traffic_light_penalty: 0.0  
    lane_invasion_penalty: -5.0
    success_reward: 30.0
    time_penalty: -0.05  
    high_speed_detection_bonus: 1.5  

  # Episode configuration
  max_episode_steps: 3000  
  success_conditions:
    distance_traveled: 5000  
    time_without_collision: 300  
    min_detection_accuracy: 0.65  

# Perception parameters
perception:
  # Detection thresholds
  min_pedestrian_confidence: 0.0  
  min_vehicle_confidence: 0.3  
  min_traffic_light_confidence: 0.0  

  # Region of interest defaults
  roi:
    default: [0.1, 0.3, 0.9, 0.7] 
    attention_scale: 2.0  

  # Detector switching thresholds
  switch_to_yolo_when:
    fps_below: 20  
    vehicles_above: 15  

  switch_to_detr_when:
    accuracy_below: 0.6
    small_objects_above: 1  

# Computational constraints
computational:
  max_inference_time: 30  
  target_fps: 20  
  energy_budget: 8000  